using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using EcommerceBackend.Core.Models;

namespace EcommerceBackend.Infrastructure.Configurations.Entities
{
    public class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            builder.HasData(
                new Product()
                {
                    Id = 1,
                    Name = "No Plan B",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205068/amazon-image/product_0_lp8pq7.jpg",
                    Attribute = "Paperback",
                    Description = "The gripping new Jack Reacher thriller from the No.1 bestselling authors Lee Child and Andrew Child.",
                    Brand = "Lee Child",
                    AverageRating = 4,
                    Ratings = 24089,
                    Price = 11.00m,
                    OldPrice = 22.00m,
                    Badge = "seller",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 2,
                    Name = "Guinness World Records 2023",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205069/amazon-image/product_1_fy5tnk.jpg",
                    Attribute = "Hardcover",
                    Brand = "Guinness World Records",
                    Description = "The 2023 edition takes readers on a journey that's out of this world! ",
                    AverageRating = 5,
                    Ratings = 929,
                    Price = 8.50m,
                    OldPrice = 22.00m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 3,
                    Name = "One: Simple One-Pan Wonders",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205069/amazon-image/product_2_dwmued.jpg",
                    Attribute = "Paperback",
                    Brand = "Jamie Oliver",
                    Description = "Give them the simplest cookbook ever this Christmas . . . Jamie's back to basics with over 120 simple, delicious, ONE pan recipes",
                    AverageRating = 4,
                    Ratings = 2993,
                    Price = 13.00m,
                    OldPrice = 23.00m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 4,
                    Name = "The Bullet That Missed: (The Thursday Murder Club 3)",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205069/amazon-image/product_3_zubcys.jpg",
                    Attribute = "Paperback",
                    Description = "Except trouble is never far away where the Thursday Murder Club is concerned. ",
                    Brand = "Richard Osman",
                    AverageRating = 5,
                    Ratings = 29283,
                    Price = 10.00m,
                    OldPrice = 20.00m,
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 5,
                    Name = "Interesting Facts For Curious Minds",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704207577/amazon-image/product_4_tnsryj.jpg",
                    Attribute = "Hardcover",
                    Description = "Want to impress your friends and family with both useful, worthless but undeniably interesting facts? ",
                    Brand = "Jordan Moore",
                    AverageRating = 4,
                    Ratings = 885,
                    Price = 10.90m,
                    OldPrice = 13.99m,
                    Badge = "limited",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 6,
                    Name = "It Start with Us",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205089/amazon-image/product_5_n8kwqi.jpg",
                    Attribute = "Paperback",
                    Description = "Colleen Hoover tells fan favourite Atlas’s side of the story and shares what comes next in this long-anticipated sequel to the #1 Sunday Times bestseller It Ends with Us ",
                    Brand = "Colleen Hoover",
                    AverageRating = 4,
                    Ratings = 44402,
                    Price = 7.00m,
                    OldPrice = 14.99m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 7,
                    Name = "SPACEBOY",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205105/amazon-image/product_6_qvypaf.jpg",
                    Attribute = "Paperback",
                    Description = "Go back to the Space Race with No.1 bestselling author David Walliams for a breathless cinematic adventure full of mystery, action, laughs and surprises ",
                    Brand = "David Walliams",
                    AverageRating = 5,
                    Ratings = 877,
                    Price = 7.00m,
                    OldPrice = 14.99m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 8,
                    Name = "Lessons in Chemistry",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205105/amazon-image/product_7_amdwix.jpg",
                    Attribute = "Hardcover",
                    Description = "Chemist Elizabeth Zott is not your average woman. In fact, Elizabeth Zott would be the first to point out that there is no such thing.",
                    Brand = "Bonnie Garmus",
                    AverageRating = 4,
                    Ratings = 62749,
                    Price = 8.00m,
                    OldPrice = 16.99m,
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 9,
                    Name = "2023 Guide to the Night Sky",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704207647/amazon-image/product_8_small_jqwaym.jpg",
                    Attribute = "Hardcover",
                    Description = "From the UK’s Number One Astronomy publisher, this is the bestselling stargazing handbook to the planets, stars and constellations visible from the northern hemisphere.",
                    Brand = "Storm Dunlop",
                    AverageRating = 4,
                    Ratings = 134,
                    Price = 4.79m,
                    OldPrice = 6.99m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 2,
                },
                new Product()
                {
                    Id = 10,
                    Name = "Fire TV Stick Lite",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205106/amazon-image/product_9_cjqxx5.jpg",
                    Attribute = "Streaming Device",
                    Description = "Our most affordable Fire TV Stick—enjoy fast streaming in Full HD. Comes with Alexa Voice Remote Lite. Easy to set up, stays hidden—plug in behind your TV, turn on the TV and connect to the internet to get set up. ",
                    Brand = "Amazon",
                    AverageRating = 4,
                    Ratings = 17602,
                    Price = 34.99m,
                    OldPrice = 40.99m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 7,
                },
                new Product()
                {
                    Id = 11,
                    Name = "BOSS Men's Prime Shirt",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205107/amazon-image/product_10_watoql.jpg",
                    Attribute = "Polo",
                    Description = "Shirt; BOSS; HUGO BOSS. 100% Cotton. Machine Wash. Fastening= Pull On. Collar Style= Classic. Slim Fit",
                    Brand = "Hugo Boss",
                    AverageRating = 3,
                    Ratings = 10,
                    Price = 42.95m,
                    OldPrice = 45.00m,
                    Stock = 1,
                    Status = true,
                    CategoryId = 5,
                },
                new Product()
                {
                    Id = 12,
                    Name = "Apple 2022 10.9-inch iPad",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205112/amazon-image/product_11_cqtsll.jpg",
                    Attribute = "iPad",
                    Description = "Striking 10.9-inch Liquid Retina display with True Tone. A14 Bionic chip with 6-core CPU and 4-core GPU. 12MP Wide back camera",
                    Brand = "Apple",
                    AverageRating = 5,
                    Ratings = 262,
                    Price = 499.00m,
                    OldPrice = 549.00m,
                    Badge = "choice",
                    Stock = 1,
                    Status = true,
                    CategoryId = 8,
                },
                new Product()
                {
                    Id = 13,
                    Name = "DeLonghi Nescafé Dolce Coffee Machine",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205112/amazon-image/product_12_cwjbfh.jpg",
                    Attribute = "Coffee Machine",
                    Description = "Over 40 beverage varieties including Nescafe Dolce Gusto or starbucks coffees. Hot and cold drink capability for hot and cold beverages prepared with one easy move of the machine’s manual lever. Easy to clean as all the coffee grinds stay in the pods there is no mess, no fuss",
                    Brand = "Nescafé",
                    AverageRating = 4,
                    Ratings = 6283,
                    Price = 34.99m,
                    OldPrice = 79.99m,
                    Badge = "limited",
                    Stock = 1,
                    Status = true,
                    CategoryId = 7,
                },
                new Product()
                {
                    Id = 14,
                    Name = "Apple iPhone 14 Pro - Deep Purple",
                    Image = "https://res.cloudinary.com/ding7zvwj/image/upload/v1704205112/amazon-image/product_13_rtlglc.jpg",
                    Attribute = "Mobile",
                    Description = "6.1-inch Super Retina XDR display featuring Always-On and ProMotion. Dynamic Island, a magical new way to interact with iPhone. 48MP Main camera for up to 4x greater resolution. Cinematic mode now in 4K Dolby Vision up to 30 fps",
                    Brand = "Apple",
                    AverageRating = 5,
                    Ratings = 1047,
                    Price = 1039.00m,
                    OldPrice = 1099.00m,
                    Badge = "seller",
                    Stock = 1,
                    Status = true,
                    CategoryId = 8,
                }
            );
        }
    }

}
